project_name: go-libyear

release:
  github:
    owner: nieomylnieja
    name: go-libyear

builds:
  - main: ./cmd/go-libyear
    binary: go-libyear
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X "main.BuildVersion={{ .Version }}" -X "main.BuildGitTag={{ .Tag }}" -X "main.BuildDate={{ .Date }}"
    env:
      - CGO_ENABLED=0

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-SHA256SUMS"
  algorithm: sha256
