name: Project checks
run-name: "Checks for ${{ github.event.pull_request.title || github.ref_name }} by @${{ github.actor }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.15.0
        with:
          enable-cache: true
      - name: Run checks
        run: devbox run -- just check
      - name: Run tests
        if: success() || failure()
        run: devbox run -- just test
