name: CI checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v4
      - name: Set up yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run spell and markdown checkers
        run: make check/spell check/trailing check/markdown
      - name: Check formatting
        run: make check/format
      - name: Run go vet
        run: make check/vet
      - name: Run golangci-lint
        run: make check/lint
      - name: Run Gosec Security Scanner
        run: make check/gosec
      - name: Run unit tests
        run: make test
